import React, { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, ShieldCheck } from 'lucide-react';
import { Badge } from '../ui/badge';

export function ContractorAnalyticsDashboard() {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState('');
  const load = () => { setError(''); fetch('/api/contractors/analytics').then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || 'Analytics unavailable'); return result; }).then((result) => setData(result.data)).catch((reason) => setError(reason.message)); };
  useEffect(load, []);
  if (error) return <div className="max-w-6xl space-y-5"><div className="bg-red-50 border border-red-200 rounded-xl p-5 text-red-900 flex gap-3"><AlertTriangle className="h-5 w-5" />{error}</div><button onClick={load} className="inline-flex items-center gap-2 text-sm font-bold text-emerald-800"><RefreshCw className="h-4 w-4" />Retry</button></div>;
  if (!data) return <div className="text-slate-500">Loading contractor analytics...</div>;
  return <div className="max-w-7xl space-y-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Phase 10</p><h1 className="text-2xl sm:text-3xl font-black">Contractor accountability</h1><p className="text-sm text-slate-500 mt-1">Server-scoped comparison for {data.jurisdiction}.</p></div><button onClick={load} aria-label="Refresh contractor analytics" className="p-2 rounded-lg border border-slate-200 bg-white hover:bg-slate-50"><RefreshCw className="h-4 w-4" /></button></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Contractors', data.summary.contractor_count], ['Projects', data.summary.project_count], ['Active works', data.summary.active_projects], ['Average indicator', data.summary.average_score ?? 'N/A']].map(([label, value]) => <div key={label as string} className="bg-white border border-slate-200 rounded-xl p-4"><div className="text-2xl font-black">{value}</div><div className="text-xs text-slate-500 mt-1">{label}</div></div>)}</div><div className="overflow-x-auto bg-white border border-slate-200 rounded-xl"><table className="w-full text-sm"><caption className="sr-only">Contractor performance comparison</caption><thead className="bg-slate-50 text-left"><tr>{['Contractor', 'Projects', 'Completed', 'Active', 'Delayed', 'Completion', 'Indicator', 'Coverage'].map((heading) => <th key={heading} scope="col" className="px-4 py-3 font-bold whitespace-nowrap">{heading}</th>)}</tr></thead><tbody>{data.contractors.map((contractor: any) => <tr key={contractor.id} className="border-t border-slate-100"><th scope="row" className="px-4 py-4 text-left font-bold whitespace-nowrap">{contractor.name}</th><td className="px-4 py-4">{contractor.total_projects_count}</td><td className="px-4 py-4">{contractor.completed_projects_count}</td><td className="px-4 py-4">{contractor.ongoing_projects_count}</td><td className="px-4 py-4">{contractor.delayed_projects_count}</td><td className="px-4 py-4">{contractor.scorecard.metrics.completion_rate}%</td><td className="px-4 py-4 font-black text-emerald-800">{contractor.scorecard.overall_score ?? 'N/A'}</td><td className="px-4 py-4"><Badge variant="secondary">{contractor.scorecard.data_sufficiency}</Badge></td></tr>)}</tbody></table></div><p className="text-xs text-slate-500 flex gap-2"><ShieldCheck className="h-4 w-4 text-emerald-700 shrink-0" />This administrative view excludes records outside the authenticated user&apos;s jurisdiction. Missing observations are not counted as zero.</p></div>;
}
