import React, { useEffect, useState } from 'react';
import { CheckCircle2, ClipboardCheck, RefreshCw, XCircle } from 'lucide-react';
import { useAuth } from '../../lib/auth/AuthContext';

export function FieldInspectionsQueue() {
  const { profile } = useAuth();
  const [inspections, setInspections] = useState<any[]>([]);
  const [message, setMessage] = useState('');
  const load = () => fetch('/api/admin/inspections?status=PENDING').then((response) => response.json()).then((result) => { if (result.success) setInspections(result.data); });
  useEffect(() => { load(); }, []);
  const review = async (id: string, status: 'VERIFIED' | 'REJECTED') => { const response = await fetch(`/api/admin/inspections/${id}/review`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-actor-id': profile?.id || '' }, body: JSON.stringify({ status }) }); const result = await response.json(); setMessage(result.success ? `Inspection ${status.toLowerCase()}.` : result.error?.message || 'Review failed'); if (result.success) load(); };
  return <div className="max-w-6xl space-y-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Phase 12 review</p><h1 className="text-2xl sm:text-3xl font-black">Field inspection queue</h1><p className="text-sm text-slate-500 mt-1">Synchronized inspections remain pending until a reviewer verifies them.</p></div><button onClick={load} aria-label="Refresh inspection queue" className="p-2 border border-slate-200 rounded-lg bg-white"><RefreshCw className="h-4 w-4" /></button></div>{message && <div role="status" className="bg-emerald-50 border border-emerald-200 rounded-xl p-4 text-sm text-emerald-900">{message}</div>}{!inspections.length && <div className="bg-white border border-dashed border-slate-300 rounded-xl p-10 text-center text-slate-500"><ClipboardCheck className="h-8 w-8 mx-auto text-slate-400" /><p className="mt-3">No pending field inspections in your jurisdiction.</p></div>}<div className="space-y-3">{inspections.map((inspection) => <article key={inspection.id} className="bg-white border border-slate-200 rounded-xl p-5"><div className="flex flex-col md:flex-row md:items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase text-slate-500">{inspection.inspection_type} · {new Date(inspection.inspection_date).toLocaleDateString('en-GH')}</div><h2 className="font-black text-lg mt-1">{inspection.inspection_reference}</h2><p className="text-sm text-slate-700 mt-2">{inspection.observations}</p><div className="text-xs text-slate-500 mt-3">Observed progress: {inspection.observed_progress_percentage}% · GPS accuracy: {inspection.gps_accuracy ? `±${Math.round(inspection.gps_accuracy)}m` : 'Unavailable'} · Sync: {inspection.sync_status}</div></div><div className="flex gap-2 shrink-0"><button onClick={() => review(inspection.id, 'VERIFIED')} className="inline-flex items-center gap-1.5 bg-emerald-700 text-white rounded-lg px-3 py-2 text-sm font-bold"><CheckCircle2 className="h-4 w-4" />Verify</button><button onClick={() => review(inspection.id, 'REJECTED')} className="inline-flex items-center gap-1.5 border border-rose-300 text-rose-800 rounded-lg px-3 py-2 text-sm font-bold"><XCircle className="h-4 w-4" />Reject</button></div></div></article>)}</div></div>;
}
