import React, { useEffect, useState } from 'react';
import { ArrowLeft, CalendarClock, CircleAlert, MapPin, ShieldCheck } from 'lucide-react';
import { Badge } from '../ui/badge';

interface ContractorProfileProps { slug: string; onNavigate: (path: string) => void; }
const metricLabels: Array<[string, string]> = [['completion_rate', 'Completion rate'], ['on_time_delivery_rate', 'On-time delivery'], ['average_progress_active', 'Average active progress'], ['resolution_rate', 'Report resolution']];

export function ContractorProfile({ slug, onNavigate }: ContractorProfileProps) {
  const [data, setData] = useState<any>(null);
  useEffect(() => { fetch(`/api/contractors/profile/${encodeURIComponent(slug)}`).then((response) => response.json()).then((result) => { if (result.success) setData(result.data); }); }, [slug]);
  if (!data) return <div className="max-w-6xl mx-auto px-4 py-16 text-center text-slate-500">Loading contractor profile...</div>;
  const { contractor, scorecard, projects } = data;
  const metrics = scorecard.metrics;
  return <div className="max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-10 space-y-8">
    <button onClick={() => onNavigate('/contractors')} className="inline-flex items-center gap-2 text-sm font-bold text-emerald-800"><ArrowLeft className="h-4 w-4" /> Contractor directory</button>
    <header className="bg-slate-900 text-white rounded-2xl p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-amber-300">Contractor profile</p><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6 mt-3"><div><h1 className="text-3xl sm:text-4xl font-black">{contractor.name}</h1><p className="text-slate-300 mt-2 max-w-2xl">{contractor.description || 'Public project delivery record on GhanaBuild.'}</p></div><div className="text-left lg:text-right"><div className="text-5xl font-black text-amber-300">{scorecard.overall_score ?? 'N/A'}</div><div className="text-xs uppercase tracking-wider text-slate-300">GhanaBuild Performance Indicator</div><Badge variant="warning" className="mt-2">{scorecard.confidence_label}</Badge></div></div></header>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{metricLabels.map(([key, label]) => { const unavailable = key === 'on_time_delivery_rate' && scorecard.pillars.delivery.metrics.on_time_rate === 'insufficient data'; return <div key={key} className="bg-white border border-slate-200 rounded-xl p-4"><div className={`text-2xl font-black ${unavailable ? 'text-slate-500 text-lg' : 'text-slate-900'}`}>{unavailable ? 'Insufficient data' : `${metrics[key]}%`}</div><div className="text-xs text-slate-500 mt-1">{label}</div></div>; })}</div>
    <section className="grid lg:grid-cols-2 gap-5"><div className="bg-white border border-slate-200 rounded-2xl p-6"><h2 className="font-black text-xl">Performance pillars</h2><div className="space-y-4 mt-5">{Object.values(scorecard.pillars).map((pillar: any) => <div key={pillar.key}><div className="flex justify-between text-sm"><span className="font-bold">{pillar.name}</span><span className="font-black">{pillar.score}/100</span></div><div className="h-2 bg-slate-100 rounded-full mt-2"><div className="h-2 bg-emerald-600 rounded-full" style={{ width: `${pillar.score}%` }} /></div><p className="text-xs text-slate-500 mt-2">{pillar.rationale}</p></div>)}</div></div><div className="bg-amber-50 border border-amber-200 rounded-2xl p-6"><div className="flex gap-3"><CircleAlert className="h-5 w-5 text-amber-700 shrink-0" /><div><h2 className="font-black text-lg">How to read this indicator</h2><p className="text-sm text-amber-950 mt-2">{scorecard.methodology.disclaimer}</p><p className="text-sm text-amber-950 mt-2">{scorecard.confidence_description}</p><p className="text-sm text-amber-950 mt-2">{scorecard.methodology.notice}</p></div></div><button onClick={() => onNavigate('/contractors/methodology')} className="text-sm font-bold text-amber-900 mt-5 underline">View full methodology</button></div></section>
    <section><div className="flex items-end justify-between gap-3 mb-4"><div><h2 className="text-2xl font-black">Verified project portfolio</h2><p className="text-sm text-slate-500">{projects.length} projects evaluated from public records.</p></div><ShieldCheck className="h-6 w-6 text-emerald-700" /></div><div className="grid md:grid-cols-2 gap-4">{projects.map((project: any) => <button key={project.id} onClick={() => onNavigate(`/projects/${project.slug}`)} className="text-left bg-white border border-slate-200 rounded-xl p-5 hover:border-emerald-400"><div className="flex justify-between gap-4"><h3 className="font-bold text-slate-900">{project.title}</h3><Badge variant="secondary">{project.project_status.replaceAll('_', ' ')}</Badge></div><div className="flex flex-wrap gap-4 text-xs text-slate-500 mt-4"><span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{project.region_name || project.region_id}</span><span className="flex items-center gap-1"><CalendarClock className="h-3.5 w-3.5" />{project.progress_percentage}% progress</span></div></button>)}</div></section>
  </div>;
}
