import React, { useEffect, useState } from 'react';
import { AlertTriangle, CircleDollarSign, Info, Search } from 'lucide-react';

interface FiscalAnalyticsDashboardProps { admin?: boolean; onNavigate?: (path: string) => void; }

export function FiscalAnalyticsDashboard({ admin = false, onNavigate }: FiscalAnalyticsDashboardProps) {
  const [data, setData] = useState<any>(null);
  const [filters, setFilters] = useState({ search: '', region: '', category: '', fiscal_year: '' });
  const [error, setError] = useState('');
  useEffect(() => {
    const params = new URLSearchParams();
    Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, value); });
    fetch(`${admin ? '/api/admin/finance-summary' : '/api/projects/finance-summary'}?${params}`)
      .then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || 'Fiscal analytics unavailable'); return result; })
      .then((result) => { setData(result.data); setError(''); }).catch((reason) => setError(reason.message));
  }, [admin, filters]);
  const setFilter = (key: keyof typeof filters, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const money = (value: number) => new Intl.NumberFormat('en-GH', { style: 'currency', currency: data?.currency || 'GHS', maximumFractionDigits: 0 }).format(value || 0);
  if (error) return <div className="bg-red-50 border border-red-200 rounded-xl p-5 text-red-900">{error}</div>;
  if (!data) return <div className="text-slate-500">Loading fiscal analytics...</div>;
  const cards = [['Allocated', data.summary.total_allocated], ['Committed', data.summary.total_committed], ['Disbursed', data.summary.total_disbursed], ['Verified expenditure', data.summary.verified_expenditure], ['Outstanding commitment', data.summary.outstanding_commitment]];
  return <div className="max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-10 space-y-8">
    <header><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">Fiscal transparency</p><h1 className="text-3xl sm:text-4xl font-black text-slate-900 mt-2">Project finance overview</h1><p className="text-slate-600 mt-2">{data.jurisdiction}. Records are aggregated server-side from the approved fiscal ledger.</p></header>
    <section aria-label="Fiscal filters" className="bg-white border border-slate-200 rounded-2xl p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
      <label className="sm:col-span-2 flex items-center gap-2 border border-slate-200 rounded-lg px-3"><Search className="h-4 w-4 text-slate-400" /><span className="sr-only">Search projects</span><input value={filters.search} onChange={(event) => setFilter('search', event.target.value)} placeholder="Search projects" className="w-full py-2 outline-none text-sm" /></label>
      <label><span className="sr-only">Region</span><select value={filters.region} onChange={(event) => setFilter('region', event.target.value)} className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm"><option value="">All regions</option>{data.by_region.map((item: any) => <option key={item.region_id} value={item.region_id}>{item.region_name}</option>)}</select></label>
      <label><span className="sr-only">Sector</span><select value={filters.category} onChange={(event) => setFilter('category', event.target.value)} className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm"><option value="">All sectors</option>{data.by_category.map((item: any) => <option key={item.category_id} value={item.category_id}>{item.category_name}</option>)}</select></label>
      <label><span className="sr-only">Fiscal year</span><input value={filters.fiscal_year} onChange={(event) => setFilter('fiscal_year', event.target.value)} placeholder="Fiscal year" inputMode="numeric" className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm" /></label>
    </section>
    <section aria-label="Fiscal summary" className="grid grid-cols-2 lg:grid-cols-5 gap-3">{cards.map(([label, value]) => <div key={label as string} className="bg-white border border-slate-200 rounded-xl p-4"><div className="text-[10px] uppercase tracking-wider text-slate-500">{label}</div><div className="text-lg font-black mt-1">{money(value as number)}</div></div>)}</section>
    <div className="grid md:grid-cols-2 gap-5"><section className="bg-white border border-slate-200 rounded-2xl p-6"><h2 className="font-black text-xl">Coverage</h2><div className="grid grid-cols-2 gap-3 mt-5"><div className="bg-emerald-50 rounded-xl p-4"><div className="text-2xl font-black text-emerald-900">{data.summary.projects_with_fiscal_records}</div><div className="text-xs text-emerald-800">Projects with fiscal records</div></div><div className="bg-slate-50 rounded-xl p-4"><div className="text-2xl font-black text-slate-900">{data.summary.projects_without_fiscal_records}</div><div className="text-xs text-slate-600">Projects without fiscal records</div></div></div></section><section className="bg-amber-50 border border-amber-200 rounded-2xl p-6"><div className="flex gap-3"><Info className="h-5 w-5 text-amber-800 shrink-0" /><div><h2 className="font-black text-amber-950">Interpretation</h2><p className="text-sm text-amber-950 mt-2">Disbursement is not automatically expenditure. Attention indicators are review prompts, not findings of wrongdoing.</p>{onNavigate && <button onClick={() => onNavigate('/finance/methodology')} className="text-sm font-bold underline mt-3">Read the methodology</button>}</div></div></section></div>
    <section className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="p-5 border-b border-slate-200"><h2 className="font-black text-xl">Funding by region</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Funding totals by region</caption><thead className="bg-slate-50 text-left"><tr><th scope="col" className="px-5 py-3">Region</th><th scope="col" className="px-5 py-3">Projects</th><th scope="col" className="px-5 py-3">Allocated</th><th scope="col" className="px-5 py-3">Committed</th><th scope="col" className="px-5 py-3">Disbursed</th><th scope="col" className="px-5 py-3">Verified expenditure</th></tr></thead><tbody>{data.by_region.map((region: any) => <tr key={region.region_id} className="border-t border-slate-100"><th scope="row" className="px-5 py-3 text-left font-bold">{region.region_name}</th><td className="px-5 py-3">{region.project_count}</td><td className="px-5 py-3">{money(region.allocated)}</td><td className="px-5 py-3">{money(region.committed)}</td><td className="px-5 py-3">{money(region.disbursed)}</td><td className="px-5 py-3">{money(region.verified_expenditure)}</td></tr>)}</tbody></table></div></section>
    <section className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="p-5 border-b border-slate-200"><h2 className="font-black text-xl">Project financial transparency</h2><p className="text-sm text-slate-500 mt-1">Financial progress is shown alongside physical progress without implying wrongdoing.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Project financial comparison</caption><thead className="bg-slate-50 text-left"><tr><th scope="col" className="px-4 py-3">Project</th><th scope="col" className="px-4 py-3">Location</th><th scope="col" className="px-4 py-3">Allocated</th><th scope="col" className="px-4 py-3">Committed</th><th scope="col" className="px-4 py-3">Disbursed</th><th scope="col" className="px-4 py-3">Physical</th><th scope="col" className="px-4 py-3">Financial</th><th scope="col" className="px-4 py-3">Status</th></tr></thead><tbody>{data.projects.map((project: any) => <tr key={project.project_id} className="border-t border-slate-100"><th scope="row" className="px-4 py-3 text-left min-w-56">{onNavigate ? <button onClick={() => onNavigate(`/projects/${project.slug}`)} className="font-bold text-emerald-800 hover:underline text-left">{project.title}</button> : project.title}<div className="text-xs text-slate-500">{project.category_name}</div></th><td className="px-4 py-3 whitespace-nowrap">{project.region_name}<div className="text-xs text-slate-500">{project.district_name}</div></td><td className="px-4 py-3 whitespace-nowrap">{money(project.total_allocated)}</td><td className="px-4 py-3 whitespace-nowrap">{money(project.total_committed)}</td><td className="px-4 py-3 whitespace-nowrap">{money(project.total_disbursed)}</td><td className="px-4 py-3">{project.physical_progress}%</td><td className="px-4 py-3">{project.financial_progress}%<div className="text-xs text-slate-500">{project.financial_physical_variance === null ? 'Insufficient data' : `${project.financial_physical_variance > 0 ? '+' : ''}${project.financial_physical_variance} pp`}</div></td><td className="px-4 py-3 font-bold">{project.attention_status}</td></tr>)}</tbody></table></div></section>
    {data.attention_flags.length > 0 && <section><h2 className="font-black text-xl flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-600" />Attention indicators</h2><div className="grid md:grid-cols-2 gap-3 mt-4">{data.attention_flags.map((flag: any, index: number) => <div key={`${flag.code}-${index}`} className="bg-amber-50 border border-amber-200 rounded-xl p-4"><div className="font-bold text-amber-950">{flag.code.replaceAll('_', ' ')}</div><p className="text-sm text-amber-900 mt-1">{flag.message}</p></div>)}</div></section>}
    <div className="text-xs text-slate-500 flex items-center gap-2"><CircleDollarSign className="h-4 w-4 text-emerald-700" />Currency totals are not converted across currencies.</div>
  </div>;
}
